# @API_URL = https://spring-boot-rob.herokuapp.com
@API_URL = http://localhost:5000

### Create tables
# GET {{API_URL}}/migrate

### Get all employees
GET {{API_URL}}/employee

### Get single employee
GET {{API_URL}}/employee/1


### Create employee
POST {{API_URL}}/employee
Content-Type: application/json

{
  "firstName": "Paula",
  "lastName": "Pintes",
  "yearlyIncome": 300000
}

### UPDATE employee
PATCH {{API_URL}}/employee/2
Content-Type: application/json

{
  "yearlyIncome": 26300
}

### DELETE employee
DELETE  {{API_URL}}/employee/1